// Generated by https://quicktype.io

export interface Graph {
  nodes: Node[];
  edges: Edge[];
}

export interface Edge {
  elementId: string;
  isRequired: boolean;
  source: string;
  target: string;
}

export interface Node {
  elementId: string;
  isRequired: boolean;
  departmentAllowed: any[];
  createdAt: CreatedAt;
  taskType: string;
  roleDisallowed: any[];
  roleAllowed: any[];
  id: string;
  title: string;
  departmentDisallowed: any[];
  isCompleted: boolean;
  status: string;
  position: Position;
}

export interface CreatedAt {
  year: Day;
  month: Day;
  day: Day;
  hour: Day;
  minute: Day;
  second: Day;
  nanosecond: Day;
  timeZoneOffsetSeconds: Day;
}

export interface Day {
  low: number;
  high: number;
}

export interface Position {
  x: number;
  y: number;
}
