// Generated by https://quicktype.io

export interface TaskGroup {
  id: string;
  destination: null;
  entry: null;
  patient: Patient;
  __typename: string;
}

export interface Patient {
  id: string;
  title: string;
  firstName: string;
  lastName: string;
  hospitalNumber: string;
  visitNumber: null;
  admitNumber: null;
  updatedAt: null;
  createdAt: string;
  __typename: string;
}
