// Generated by https://quicktype.io

export interface User {
  id: string;
  username: string;
  title: string;
  firstName: string;
  lastName: string;
  role: string;
  department: string;
  updatedAt: string;
  createdAt: string;
}
